-- MySQL Script generated by MySQL Workbench
-- Wed Mar 27 11:23:09 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema gamesimulationdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gamesimulationdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gamesimulationdb` DEFAULT CHARACTER SET utf8mb4 ;
USE `gamesimulationdb` ;

-- -----------------------------------------------------
-- Table `gamesimulationdb`.`games`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gamesimulationdb`.`games` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `status` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name` (`name` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `gamesimulationdb`.`teams`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gamesimulationdb`.`teams` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name` (`name` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `gamesimulationdb`.`gameteams`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gamesimulationdb`.`gameteams` (
  `game_id` INT(11) NOT NULL,
  `team_id` INT(11) NOT NULL,
  PRIMARY KEY (`game_id`, `team_id`),
  INDEX `team_id` (`team_id` ASC),
  CONSTRAINT `gameteams_ibfk_1`
    FOREIGN KEY (`game_id`)
    REFERENCES `gamesimulationdb`.`games` (`id`),
  CONSTRAINT `gameteams_ibfk_2`
    FOREIGN KEY (`team_id`)
    REFERENCES `gamesimulationdb`.`teams` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `gamesimulationdb`.`turns`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gamesimulationdb`.`turns` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `game_id` INT(11) NOT NULL,
  `turn_number` INT(11) NOT NULL,
  `submission_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `game_id` (`game_id` ASC),
  CONSTRAINT `turns_ibfk_1`
    FOREIGN KEY (`game_id`)
    REFERENCES `gamesimulationdb`.`games` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
